### ISSUE TITLE
[Feature Request] Allow integration to be set up without user/access code sensors

### ISSUE THREAD

**Issue by smiller171** [FutureTense/lock-manager#35]
**Is your feature request related to a problem? Please describe.**
I unfortunately can't set up this integration because my lock doesn't seem to report a user code sensor or access code sensor

**Describe the solution you'd like**
I'd like to be able to install the integration without these sensors, disabling any features related to counting entries.

**Describe alternatives you've considered**
Using fake sensors to trick the integration into thinking I have the right sensors available.

**Additional context**
I'm using a very old Yale Real Living z-wave lock. Doesn't even have z-wave plus

**Comment by firstof9** [comment]
Are you using `ozw` or `zwave`?

**Comment by smiller171** [comment]
I'm using `zwave`

**Comment by firstof9** [comment]
You should see an `alarm_type` and `alarm_level` sensor.

**Comment by smiller171** [comment]
I was imagining something entirely different, thanks
