### ISSUE TITLE
Problem with integration

### ISSUE THREAD

**Issue by jjmuriel** [FutureTense/lock-manager#37]
Hi, 
I have this problem when I create the integration "lock-manager": "User input malformed". Can somebody said me what i doing wrong?  Thanks.
Note : I have a Z-Wave Door/Window Sensor by Ecolink (dwzwave2-eco) and a lock BE469ZP Connect Smart Deadbolt
by Schlage (Allegion).

![Problem](https://user-images.githubusercontent.com/17131600/97239288-36c1ef00-17b9-11eb-9898-5412523afcb2.jpg)

**Comment by firstof9** [comment]
You didn't select a user code sensor or a access control sensor.

**Comment by jjmuriel** [comment]
> You didn't select a user code sensor or a access control sensor.

There is no options to select in this two fields.

**Comment by firstof9** [comment]
[See the wiki](https://github.com/FutureTense/lock-manager/wiki/Troubleshooting#missing-sensors).

**Comment by jjmuriel** [comment]
> [See the wiki](https://github.com/FutureTense/lock-manager/wiki/Troubleshooting#missing-sensors).

Thank you
