### ISSUE TITLE
ISSUE: Not all features work for Schlage FE599 locks

### ISSUE THREAD

**Issue by Leaffan467** [FutureTense/lock-manager#38]
As far as I can see features that do not work are status report, notifications and limit access count.

Looking at the code in sidedoor_lock_manager_common.yaml the below information is different than what is there for schlage locks although similar to qwikset.

Informaion I have for this lock.

Lock:
lock.schlage_allegion_fe599gr_wireless_door_lock_locked

User code sensor:
sensor.schlage_allegion_fe599gr_wireless_door_lock_alarm_level

Access control sensor:
sensor.schlage_allegion_fe599gr_wireless_door_lock_alarm_type
Note 16 = Keypad unlock

**Comment by firstof9** [comment]
The fe599 is an edge case.
The code should have been added for unlock on this lock already.

**Comment by Leaffan467** [comment]
It does lock, unlock, set and delete usercodes. Just status report, notifications and limit access count do not work as far as I can tell.

**Comment by Leaffan467** [comment]
Correction, user codes are no longer added or deleted (possibly broken after ver .29). Can add and delete manually by calling service lock.set_usercode

**Comment by firstof9** [comment]
> Correction, user codes are no longer added or deleted (possibly broken after ver .29). Can add and delete manually by calling service lock.set_usercode

https://github.com/FutureTense/lock-manager/wiki/Troubleshooting#unable-to-set-codes

**Comment by Leaffan467** [comment]
Troubleshooting this and believe I found a typo in the easy mode ZWave Package File. "automations:" should be "automation:"

Also indentation in the allow automation binary sensor seems incorrect

**Comment by firstof9** [comment]
The examples have been updated now. Thank you.
Has your issue been resolved? (Other than the code mismatch)

Also 16 = Unlock, does 18 = Lock?

**Comment by Leaffan467** [comment]
Missed the indentation for the binary sensor "allow_automation" think you need a couple extra spaces in front of the friendly name and value template.

    binary_sensor:
        - platform: template
          sensors:
          allow_automation:
            friendly_name: "Allow Automation"
            value_template: "{{ is_state('input_boolean.allow_automation_execution', 'on') }}"    

Also in the below automation for the zwave version, condition calling for state of binary_sensor.ozw_network_status won't work because it is not ozw, also missing 'n' in execution last word:

    - alias: open_zwave_network_up
      initial_state: true
      trigger:
        - platform: homeassistant
          event: start
        - platform: event
          event_type: zwave.network_start
      condition:
        - condition: state
          entity_id: binary_sensor.ozw_network_status
          state: "on"
      action:
        - service: homeassistant.turn_on
          entity_id: input_boolean.allow_automation_executio`

**Comment by firstof9** [comment]
Thanks updated.

**Comment by Leaffan467** [comment]
Had to add more indents to:

    binary_sensor:
        - platform: template
          sensors:
            allow_automation:
              friendly_name: "Allow Automation"
              value_template: "{{ is_state('input_boolean.allow_automation_execution', 'on') }}"  

No errors and "Allow Autmation" set to "on" after restart but still cannot set or delete codes. Nothing shows in the zwave logs so looks like nothing is being sent to the lock. Lock & unlock work.

**Comment by firstof9** [comment]
Anything in the Home Assistant logs?

**Comment by Leaffan467** [comment]
Nothing relevant I can see in the server logs.

Logbook has 3 entries after enabling a door code:
- Enabled turned on (noticed there are "input_boolean.enabled_sidedoor" for each unlock code, all have the same friendly name of "Enabled")
- enabled_sidedoor_1 turned on
- status was connected

Looks like the automation to set the user code is not firing.

**Comment by Leaffan467** [comment]
Looking in sidedoor_lock_manager_common.yaml, the only place where lock.set_usercode shows up is commented out...

**Comment by firstof9** [comment]
@FutureTense is working on the script portions. Keep an eye out for 0.0.33.

**Comment by firstof9** [comment]
Looks like we need to make a workaround for this specific lock as well.

**Comment by firstof9** [comment]
Work around is in the 0.0.40 code, your lock code is another story, would you be able to post the `CommandClass 113` from your `zwcfg_xxxx.xml` file for your lock?

**Comment by Leaffan467** [comment]
<CommandClass id="113" name="COMMAND_CLASS_ALARM" version="1" request_flags="2" issecured="true">
    	<Instance index="1" />
    	<Value type="byte" genre="user" instance="1" index="0" label="Alarm Type" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="16" />
    	<Value type="byte" genre="user" instance="1" index="1" label="Alarm Level" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="1" />
    </CommandClass>

**Comment by firstof9** [comment]
Are you able to confirm if code 18 = Keypad Lock?

**Comment by Leaffan467** [comment]
Cannot lock my lock from keypad, only from the lock & unlock buttons on the inside. Only code that shows up is 16 = User code unlock and this only unlocks for 5 seconds.

**Comment by firstof9** [comment]
Ah ok, we'll I'll get that added.
