### ISSUE TITLE
ISSUE: User Input Malformed

### ISSUE THREAD

**Issue by Resterday** [FutureTense/lock-manager#60]
**Describe the bug**
While trying to complete the configuration of Lock-Manager I keep getting the following error when submitting: "User input malformed". 

**Environment (please complete the following information):**

- OS: HassOS
- Type of device: RPi4
- Home Assistant version: 117.2
- Hassio
- Component version: .40

**Logs**
No logs

**Screenshots**
![image](https://user-images.githubusercontent.com/13279768/98633498-65ba8380-22d6-11eb-9b9f-c34a37a0b1d9.png)

**Additional context**
Do I need to make a selection from "User Code Sensor (from lock)" and "Access Control Sensor (from lock)"? The dropdown doesn't let me make any selection and I do not see any sensors in my entity register that matches the example you have in repo. Wondering if this may be an incompatibility with my lock type, Yale?

**Comment by firstof9** [comment]
Please [see the wiki](https://github.com/FutureTense/lock-manager/wiki/Troubleshooting#missing-sensors).

**Comment by lemieux** [comment]
The wiki covers `ozw` which is the new OpenZwave integration..? Not too sure how to get those sensor using the old Zwave integration.

**Comment by firstof9** [comment]
They're there, you may have changed their entity names.
