### ISSUE TITLE
ISSUE: Not compatible with v 1.0 beta

### ISSUE THREAD

**Issue by FuzzyMistborn** [FutureTense/lock-manager#67]
**Describe the bug**
I just fired up a version of the beta build to test something else and figured while I was at it experiment with this component.  I added the component via HACS but when I restarted/went to the add integration page, the "lock-manager" component was there.  Reverted back to the stable release (.118.4) and it showed back up.  Didn't see any errors in the log.

**Environment (please complete the following information):**

- OS: [e.g. HassOS/Raspbian/CentOS] Ubuntu
- Type of device: [e.g. RPi3/NUC/Synology] x86 server
- Home Assistant version: [e.g. 0.105.5] 1.0b0
- Hassio/Docker/Core? Docker
- Component version: [e.g. 0.1.2] 0.0.43

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
This is likely due to the name being "lock-manager". Hence the topic has been brought up to rename it.

**Comment by firstof9** [comment]
Currently installed and loaded integrations work fine at this time.
I'm going to test reinstalling the integration on my dev instance to see if I can reproduce.

**Comment by firstof9** [comment]
I can't reproduce it in the dev instance:
![image](https://user-images.githubusercontent.com/1105672/100953326-9b1a5180-34cf-11eb-957d-6136f5708dae.png)

Also it does show up for me in 1.0b0 🤷

**Comment by firstof9** [comment]
Try hitting F5 when in the integrations screen, then try the `+ Add Integration` see if that works @FuzzyMistborn

**Comment by FuzzyMistborn** [comment]
.....I swear I tried that......thanks!
