### ISSUE TITLE
Lock-Manager configuration

### ISSUE THREAD

**Issue by ghost** [FutureTense/lock-manager#72]
After installing Lock-Manager, the configuration screen does not appear as it used to.  Not allowing you to enter the name of the lock, code slots, start from code slot #, etc.

![image](https://user-images.githubusercontent.com/44730909/101382618-2ad04f00-3886-11eb-803d-0cdcf05a1b16.png)

**Comment by firstof9** [comment]
Press F5 while in the integrations screen, then press the `+`

**Comment by ghost** [comment]
Hi,Thanks for the quick response.  Tried F5, didn't work and tried to reinstall then F5 still didn't work.
Tom

    On Monday, December 7, 2020, 12:28:15 PM EST, Chris <notifications@github.com> wrote:  
 
 


Press F5 while in the integrations screen, then press the +

**Comment by firstof9** [comment]
Check your home assistant logs for errors.

**Comment by ghost** [comment]
Chris,Thanks again for the quick reply.  It's a shame companies to respond so well.
I am relative new with Home Assistant.  I have searched every log I can find.  No errors regarding Lock-Manager.
I really appreciate your help.  What ever I can do, just let me know.
I installed it about a month ago and it worked fine.  Since I have reinstalled Home Assistant and starting over.

Thanks,Tom

    On Monday, December 7, 2020, 1:38:09 PM EST, Chris <notifications@github.com> wrote:  
 
 


Check your home assistant logs for errors.

**Comment by firstof9** [comment]
Did you install lock-manager with HACS?

**Comment by ghost** [comment]
Chris,Yes, I have installed it several times using HACS
ThanksTom

    On Monday, December 7, 2020, 2:30:41 PM EST, Chris <notifications@github.com> wrote:  
 
 


Did you install lock-manager with HACS?

**Comment by firstof9** [comment]
So when you go to Configuration -> Integrations and click the `+` does lock-manager not show up when you search for it?

**Comment by ghost** [comment]
Chris,
Yes, it appears and installs. There is no way from there to get the configuration screen.

Thanks,Tom
    On Monday, December 7, 2020, 2:40:43 PM EST, Chris <notifications@github.com> wrote:  
 
 


So when you go to Configuration -> Integrations and click the + does lock-manager not show up when you search for it?

**Comment by firstof9** [comment]
What do you mean? If you can't get to the configuration screen that's going to be a Home Assistant issue.

Just to be clear the configuration screen is this:
![image](https://user-images.githubusercontent.com/1105672/101400480-37f13c00-388e-11eb-9872-6224352d87a7.png)

**Comment by ghost** [comment]
Chris,Thanks for your help.  I reinstalled again and its working.  Thanks a million.
Tom

    On Monday, December 7, 2020, 3:15:24 PM EST, Chris <notifications@github.com> wrote:  
 
 


What do you mean? If you can't get to the configuration screen that's going to be a Home Assistant issue.

Just to be clear the configuration screen is this:

**Comment by ghost** [comment]
Chris,Well I got further.  I got the config screen up.  Filled it in.  It created the folder packages/lock-manager/frontdoor and created frontdoor_lockmanager_common.yaml.  That yaml file is empty and nothing in my lovelace file.  It did create 3 entities frontdoor_code_slot_1 (2 and 3)
Tom

    On Monday, December 7, 2020, 3:15:24 PM EST, Chris <notifications@github.com> wrote:  
 
 


What do you mean? If you can't get to the configuration screen that's going to be a Home Assistant issue.

Just to be clear the configuration screen is this:

**Comment by firstof9** [comment]
None of the files in the package directory should be empty.

**Comment by ghost** [comment]
Chris,The only folder in packages is lock-manager and the only folder in lock-manager is frontdoor.  In the folder frontdoor is one file frontdoor_lock_manager_common.yaml and it is emptyTom

    On Monday, December 7, 2020, 3:48:41 PM EST, Chris <notifications@github.com> wrote:  
 
 


None of the files in the package directory should be empty.

**Comment by firstof9** [comment]
The Home Assistant log should have some kind of error if we're having trouble writing the file out, or your integration didn't download correctly.

**Comment by ghost** [comment]
Chris,
I Deleted lock_master folder
I Deleted Lock-Master integrationI Installed Lock-Master integrationI Completed the configuration screen (lock name, code slots, etc)I Hit SubmitDialog box Sucess Created configuration for frontdoor came up
I  Hit Finish
frontdoor_lock_manager_common.yaml is empty file


Error Log:2020-12-07 16:45:31 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall lock-manager.generate_package (c:15d2f91591508f4ad42101b07153c775): lockname=frontdoor>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1467, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/lock-manager/__init__.py", line 288, in _generate_package
FileNotFoundError: [Errno 2] No such file or directory: '/config/custom_components/lock-manager/lock_manager_common.yaml'
I hope this helps.Tom

    On Monday, December 7, 2020, 4:37:51 PM EST, Chris <notifications@github.com> wrote:  
 
 


The Home Assistant log should have some kind of error if we're having trouble writing the file out, or your integration didn't download correctly.

**Comment by firstof9** [comment]
Somehow you're missing a file from the component.

**Comment by ghost** [comment]
Chris,Any suggestion on what to do?
Tom

    On Monday, December 7, 2020, 5:37:51 PM EST, Chris <notifications@github.com> wrote:  
 
 


Somehow you're missing a file from the component.

**Comment by firstof9** [comment]
You could try manually placing the files in the directory from github.

**Comment by DLThompson06** [comment]
I too am having a problem getting the keymaster configuration screen to come up.  I've completed all of the pre-installation steps, installed the keymaster integration, restarted Home Assistant, then gone into configuration/integrations but keymaster (or lock-manager) aren't in there.  The only message I get is a warning, not an error:

> You are using a custom integration keymaster which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

I've checked the packages folder and the only thing in there is the lock_manager_additional_yaml folder with the zwave.yaml file in it from the pre-installation steps.  I'm also using the latest version of Home Assistant.  I've tried the F5 + but that doesn't do anything either.  What am I missing?  Sorry if this is obvious, I'm still a relative newbie in Home Assistant.  Thanks.

**Comment by firstof9** [comment]
Have you tried F5 while in the integrations screen specifically?

**Comment by DLThompson06** [comment]
> Have you tried F5 while in the integrations screen specifically?

Yes, it just wants to turn my screen brightness down.  I'm on a Mac.  I've also tried holding the fn key down with the F5 and it doesn't do anything either.

**Comment by DLThompson06** [comment]
Okay, I got it figured out but wow do I feel foolish.  I was searching my installed integrations instead of adding a new integration.  Duh.  Thanks for trying to help and sorry for wasting your time!
