### ISSUE TITLE
[Feature Request] Notification when door is locked

### ISSUE THREAD

**Issue by groto27** [FutureTense/lock-manager#73]
I would like to be notified when the door is locked and who locked it.

Even better, could we have the ability to toggle which notifications we want to receive so that those that want just unlocked vs locked notifications can choose?

**Comment by firstof9** [comment]
Keep in mind not all locks support a "who locked" the door, on my lock for instance, if you just push the lock button from the outside it'll say `user 1` locked the door. Some report `user 0` who locked it when locked externally as well.

**Comment by groto27** [comment]
Sure. I am using a Schlage be469zp. I was hoping the notification would display what was entered in the "Name" field within the Lovelace UI for those locks that support it.

**Comment by firstof9** [comment]
Does your lock require you to enter a PIN to lock it from the outside?

**Comment by groto27** [comment]
Good point. You just press a button and it locks. Then maybe it would be better to just say "Door locked"

**Comment by firstof9** [comment]
I currently get "Door Locked" notifications.

**Comment by FutureTense** [comment]
My notifications haven’t been working for some time, but IIRC there are two ways of getting notifications when doors are locked/unlocked.  The first is generic locked/unlocked notifications and that is controlled by the first input boolean on the badges.  The second is slot notifications.  Each code slot allows notifications to be sent if the slot’s PIN is used to change the lock state.  So if Slot 1 is “Penny 1234, notifications ON” and 1234 is used your devices should get notifications sent to them like “Penny unlocked frontdoor” when 1234 was used to unlock the frontdoor.  Likewise, if 1234 is used to lock that door, you should get a similar message.

Are you not experiencing this?  I also recall I was having a pain dealing with some of the messaging.  Like I didn’t want two notifications sent when a door was unlocked and both lock notification settings were on.

**Comment by groto27** [comment]
I have seen messages that say RF Lock and then the person's name. What is RF?

Also I have seen notifications where it says "Manual Lock" and the person's name. Is the manual lock notification when someone hits the SCHLAGE button to lock the Schlage Connect for example? Not sure

**Comment by firstof9** [comment]
> What is RF?

Radio Frequency, basically locked via ZWave Command.



> Is the manual lock notification when someone hits the SCHLAGE button to lock the Schlage Connect for example?

"Manual Lock" is when someone inside locks the door or via the outside "lock" procedure. Some locks always associate this with User 1.
