### ISSUE TITLE
ISSUE: Lock-Manager Config

### ISSUE THREAD

**Issue by Knoxie** [FutureTense/lock-manager#75]
**Describe the bug**
I do not have the UI option to check 'OZW' in the integrations screen, and cannot get the integration to connect to my locks for pin sync/setting.

**Environment (please complete the following information):**

- OS: Home Assistant Container
- Type of device: Unraid Docker
- Home Assistant version: 2021.1.0.dev20201224
- Hassio/Docker/Core? Docker - Unraid
- Component version: [e.g. 0.1.2]

**Logs**
Paste your error logs here.

**Screenshots**

![image](https://user-images.githubusercontent.com/1057404/103101229-89b2f980-45e4-11eb-842d-12bb6d342bdc.png)

**Additional context**
Kwikset Z-wave doorlock

**Comment by firstof9** [comment]
The option is removed as it's automatically detected internally now.
