### ISSUE TITLE
ISSUE: setting user code never moves beyond "connecting"

### ISSUE THREAD

**Issue by autumnwalker** [FutureTense/lock-manager#76]
**Describe the bug**
When attempting to set user code 1 on one of my my Schlage BE469 locks it never moves beyond "connecting". No errors shown in logs. Works fine on my other BE469. Code slots 2 and 3 work fine.

**Environment (please complete the following information):**

- OS: Home Assistant Container
- Type of device: Docker
- Home Assistant version: 2020.12.1
- Hassio/Docker/Core? Docker
- Component version: 0.0.45

**Logs**
N/A

**Comment by firstof9** [comment]
`ozw` or `zwave` ?

**Comment by autumnwalker** [comment]
zwave as built with 2020.12.1.

I saw the preference for ozw, but I already had a zwave network built.

**Comment by firstof9** [comment]
`zwave` and the BE469 locks have a love/hate relationship with each other, they don't always work correctly.
Fortunately they seem to work flawlessly in `ozw`, so that is the ultimate fix at this time.

**Comment by belav** [comment]
I left this comment on another issue, I was able to get past the stuck connecting state by using Reset Code Slot under the advanced options section. I'm using ozw, so I'm not sure if that would affect it.
