### ISSUE TITLE
ISSUE: mqtt.binary_sensor: Unable to set up component

### ISSUE THREAD

**Issue by socal0001** [FutureTense/lock-manager#78]
**Describe the bug**
using ozw, download 
https://raw.githubusercontent.com/FutureTense/lock-manager/master/assets/lock_manager_additional_yaml/ozw.yaml
into packages/lock_manager_additional_yaml/
restart home assitant, get error

Logger: homeassistant.setup
Source: setup.py:280
First occurred: 6:57:24 PM (1 occurrences)
Last logged: 6:57:24 PM

Unable to prepare setup for platform mqtt.binary_sensor: Unable to set up component.

**Environment (please complete the following information):**

- OS: Debian GNU/Linux 10 (buster)
- Type of device: NUC
- Home Assistant version: 2020.12.2
- Hassio/Docker/Core? Home Assistant Supervised
- Component version: latest as of 1/4/2021

**Logs**
2021-01-04 19:31:23 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-04 19:31:25 ERROR (MainThread) [homeassistant.setup] Setup failed for mqtt: Integration failed to initialize.
2021-01-04 19:31:25 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform mqtt.binary_sensor: Unable to set up component.
2021-01-04 19:31:32 ERROR (MainThread) [custom_components.hacs] custom-components/sensor.rpi_power - Repository is archived.

**Additional context**
Other portions of ozw.yaml installed fine.
Although I have HACS installed, this install is not an install from HACS.  I had tried it and ran into this error.  I could not figure out what it was so started manually and found this.

**Comment by firstof9** [comment]
> 2021-01-04 19:31:25 ERROR (MainThread) [homeassistant.setup] Setup failed for mqtt: Integration failed to initialize.

Are you using the OpenZWave beta integration? If so you're MQTT integration doesn't appear to be setup and you're going to have a bad time.

If you're not using the OpenZWave beta, you've grabbed the wrong YAML file.

**Comment by socal0001** [comment]
Yes, using OpenZWave beta integration.

**Comment by firstof9** [comment]
Check your MQTT config, HA says it's not working.

**Comment by socal0001** [comment]
It seems the latest OpenZWave beta integration does not include MQTT the way your system require it.  I sourced this information from here:

https://community.home-assistant.io/t/openzwave-beta-add-on-how-to-set-association-group/263142/11

Relevant comment:
The original release of the OZW Beta required (in the context of a Supervised install):
The Mosquitto addon
The OZW addon
The MQTT integration, configured to connect to the Mosquitto addon broker
The OZW integration

The latest version of HA can skip MQTT entirely (only in the context of a Supervised install). This is the installation method OP has used. Therefore the minimum requirements are now:
The OZW addon
The OZW integration

I will look into how to add MQTT and there are comments in the referenced threads.  If you have suggestions, I'm all ears.

**Comment by socal0001** [comment]
I don't know how to add MQTT that will connect with the OZW that I have installed.  Since the latest version skips MQTT entirely, do you have suggestions on how I can proceed/test something that will then work for future users of your great software?

**Comment by firstof9** [comment]
https://www.home-assistant.io/integrations/mqtt/

**Comment by socal0001** [comment]
Got it, I will review this week and post a solution if I can get it to work so future users can benefit.  Thanks for helping me!

**Comment by socal0001** [comment]
Was easy, just 
1. go to Supervisor and add the Mosquitto broker.
2. go to configuration, then intergrations and there will be a new option for MQTT, adding accepting defaults.
3. Wait a few minutes for thing to settle, then I restarted server and everything worked.
Thanks for the help kind people.
