### ISSUE TITLE
ISSUE: Door Report is often not accutate

### ISSUE THREAD

**Issue by ptdalen** [FutureTense/lock-manager#79]
**Describe the bug**
For many versions I have had to add a 500ms delay to the door report.

Like so
  - alias: frontdoor Status Report
    trigger:
      platform: state
      entity_id: input_number.frontdoor_lock_command, input_number.frontdoor_lock_user
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
      - condition: template
        value_template: "{{ states('sensor.front_door_deadbolt_access_control') != 0 }}"
    action:
      **- delay:
          milliseconds : 500**

This is for schalge be469 older version. Not zwave plus. 

I have tried 250ms delay and it was not consistent.  500ms seems to always work for me, and seems like would not be a big deal even for other locks that may or may not occasionally have this issue.

Without the delay, the input text for the report ends up reporting the previous state.

**Comment by firstof9** [comment]
I wonder if this will be an issue in the latest code.

**Comment by ptdalen** [comment]
It's possible.  I will say for me it's been a needed addition as long as I have been using this.  It's not a big deal, but 1/2 a second seems like a good safety measure to handle slower updates.  Not sure if zwave is slow to report/update or if it's HA.  Either way, this has worked for me.  I am running 2021.1.0 and .45 of lock manager, running on an i3 NUC, docker version of HA and OZW.

**Comment by firstof9** [comment]
I think the messages fire at almost the same time, but ozw is queued them for reporting. That's my suspicion.
