### ISSUE TITLE
ISSUE: Stuck on connecting when trying to add a new code

### ISSUE THREAD

**Issue by GenericGames** [FutureTense/lock-manager#80]
**Describe the bug**
Stuck on connecting when trying to add a new code.

**Environment (please complete the following information):**

- OS: HassOS
- Type of device: RPi4
- Home Assistant version: 2021.1.1
- Hassio/Docker/Core?
- Component version: [e.g. 0.1.2]

**Logs**
Paste your error logs here.

**Screenshots**
Posted below

**Additional context**
I'm very new to home assistant and I'm trying to get lock-manager to work but I've been having some issues. I'll just outline the steps I did below.

I added to the `configuration.yaml`
```sh
homeassistant:
  packages: !include_dir_named packages
```

created the `packages` dir, made `lock_manager_additional_yaml` and added the [text from here](https://github.com/FutureTense/lock-manager/blob/master/assets/lock_manager_additional_yaml/ozw.yaml) I installed lock-manager via HACS. 

created the intergrations with these settings: 
https://i.imgur.com/6czN4Kw.png
https://i.imgur.com/t0YiXEk.png
https://i.imgur.com/H0jprY9.png

I added Lovelace-auto-entities, lovelace-card-tools, and lovelace-fold-entity-row via HACS

I copy and pasted the lovelace file into the dashboard configuration and than tried to add a test code and it's stuck on connecting

https://i.imgur.com/BMD0Ug9.png

**Comment by rohitpaul** [comment]
I have the same issue. Just installed with zwave Yale lock.

**Comment by tmmedic20** [comment]
Same issue here,

I have 3 locks, 2 of them "connected" fine with all 5 codes I input.

3rd lock will connect with 2 of the codes but the last 3 stay on "connecting"

I've removed the lock and factory reset it several times with no changes in behavior.

All 3 are Schlage Connect locks.

**Comment by TedX33** [comment]
Having the same issue.  I had only been trying with Code1.  I tried to enter a code in Code2 and surprisingly it connected and worked.  Code1 is successfully reading the code that's already stored, but won't change the code.  Only the Code2 slot seems to work.  Nothing being reported in the logs after changing level to debug.

**Comment by belav** [comment]
I have a be469zp schlage connect lock. I'm using ozw and all my codes get stuck at a connecting state.

Just now I noticed "reset code slot" under advanced. After turning that on it appears the I can now update the pin and everything connects.

**Comment by tmmedic20** [comment]
So after a few hours of reading and re-reading the pre-installation requirements, and the troubleshooting page on the wiki........

I go to look at the ozw.yaml file and make sure its completely correct and notice in VSC it shows as OZW.yaml.txt

I just about hit myself with a sledgehammer over this.   Been weeks trying to figure this out over some silly mistake!


Lesson learned   double check .yaml file extensions!
