### ISSUE TITLE
ISSUE:  Helper objects and automations aren't removed when integration is removed.

### ISSUE THREAD

**Issue by jayscovill** [FutureTense/lock-manager#82]
**Describe the bug**
When I removed the locks then the integration from Configuartion -> Integrations and HACS the hundreds of helper objects such as input_boolean.* and input_datetime.* that were created aren't removed from Configuration -> Helpers.

I would like to be able to remove them on mass but I can't find what file they are stored in in my HASS installation.  I've searched under .storage but cannot locate those entries anywhere.

**Environment (please complete the following information):**

- OS: HASSOS 5.11
- Type of device: VM
- Home Assistant version: 2021.02.11
- supervisided
- Component version: latest from HACS

**Comment by firstof9** [comment]
Did you check the `packages` directory?
That's where the template'ed files get placed.

**Comment by jayscovill** [comment]
Yes, I've removed the files there but they are still persisting in the Helpers section.

**Comment by firstof9** [comment]
And just to confirm the process you used you followed the steps:

1. Navigated to `Configuration` -> `Integrations`
2. Clicked the "Overflow menu" (3 dots)
3. Selected "Delete" on the KeyMaster integration

That sound about right?

**Comment by jayscovill** [comment]
Yep, after deleting each lock from the integration.

**Comment by firstof9** [comment]
Sounds like the unload_entry function didn't get fired like it's supposed to, this function has all the cleanup in it to remove the entities.

EDIT: Did you get a persistent notification stating it was "removing the lock and the files generated for it"?

**Comment by jayscovill** [comment]
No, no persistent notification.

**Comment by jayscovill** [comment]
Ok, I just did a complete restart of HassOS/Home Assistant versus just restarting Home Assistant and they have now gone away.  So it looks a reboot of HassOS might be needed after the integration is removed.

**Comment by jayscovill** [comment]
So as another data point when I restart Hass the helper objects don't appear until after the loading integrations message disappears.  Versus the others that I created that are there as soon as Hass has finished booting. So it appears there's still remnants of the integration lingering that are still being loaded.  I don't see any mention of 'keymaster' in the logs though.

**Comment by jayscovill** [comment]
Gah, they were in core.entity_registry.  I swear I'd check it...but problem solved.  Thanks!
